apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 6
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:cluster 
        volumeMounts:
        - mountPath: /etc/redis
          name: config
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
      volumes:
      - name: config
        configMap:
          name: redis-cluster-config
          items:
          - key: redis-config
            path: redis.conf


