---
- hosts: local-test
  remote_user: root
  tasks:
    - name: copy the shell file to /usr/local/bin
      sudo: yes
      copy: src=./dockerd.sh dest=/usr/local/bin

    - name: add +x mode of the file
      sudo: yes
      file: dest=/usr/local/bin/dockerd.sh mode=a+x 

    - name: copy the service file to /etc/systemd/system
      sudo: yes
      copy: src=./dockerd.service dest=/etc/systemd/system

    - name: force systemd to reread configs
      sudo: yes
      systemd: daemon_reload=yes

    - name: start dockerd
      sudo: yes
      systemd:
        name: dockerd.service
        state: started
